import { StyleSheet } from "react-native";

export const colors = {
  background: "#F5F7FB",
  card: "#FFFFFF",
  primary: "#2563EB",
  primaryDark: "#1E40AF",
  sky: "#0EA5E9",
  text: "#102033",
  muted: "#64748B",
  border: "#DBE3EF",
  danger: "#B91C1C",
  dangerBg: "#FEF2F2",
  successBg: "#D1FAE5",
  successText: "#047857",
  warningBg: "#FEF3C7",
  warningText: "#92400E",
};

export const globalStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
  },
  center: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  title: {
    fontSize: 32,
    fontWeight: "900",
    color: colors.text,
    lineHeight: 38,
  },
  subtitle: {
    marginTop: 10,
    fontSize: 15,
    color: colors.muted,
    lineHeight: 24,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#0F172A",
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  input: {
    height: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: "#F8FAFC",
    color: colors.text,
    fontSize: 15,
  },
  label: {
    fontSize: 13,
    color: colors.text,
    fontWeight: "800",
    marginBottom: 8,
  },
  button: {
    height: 54,
    borderRadius: 999,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  ghostButton: {
    height: 46,
    borderRadius: 999,
    backgroundColor: "#EEF4FF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  ghostButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: "900",
  },
  errorBox: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.dangerBg,
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  errorText: {
    color: colors.danger,
    fontWeight: "700",
    lineHeight: 20,
  },
});
